import sqlite3

def veri_ekle():
    # Veritabanı bağlantısı
    conn = sqlite3.connect('veritabani.db')
    
    # İmleç oluşturma
    c = conn.cursor()

    # Veritabanına veri ekleme
    #Dünya Klasik-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    veriler = [
        ('suc', '/dklasik'),
        ('Suc ve ceza', '/dklasik'),
        ('Suc ve Ceza', '/dklasik'),
        ('suc ve ceza', '/dklasik'),
        ('Fyodor Dostoyevski', '/dklasik'),
        ('Fydor', '/dklasik'),
        ('fydor', '/dklasik'),
        ('dostoyevski', '/dklasik'),
        ('Dostoyevski', '/dklasik'),
        ('Suc ve Ceza Fyodor Dostoyevski', '/dklasik'),
        ('suc ve ceza fydor dostoyevski', '/dklasik'),
        ('suc ve ceza dostoyevski', '/dklasik'),
        ('Suc ve Ceza Dostoyevski', '/dklasik'),
        
        ('Sefiller', '/dklasik'),
        ('sefiller', '/dklasik'),
        ('Victor Hugo', '/dklasik'),
        ('victor hugo', '/dklasik'),
        ('sefiller  victor hugo', '/dklasik'),
        ('Sefiller  Victor Hugo', '/dklasik'),
        ('Sefiller  victor hugo', '/dklasik'),
        
        ('Anna', '/dklasik'),
        ('anna', '/dklasik'),
        ('Karenina', '/dklasik'),
        ('karenina', '/dklasik'),
        ('Anna Karenina', '/dklasik'),
        ('anna karenina', '/dklasik'),
        ('Anna Karenina  Lev Tolstoy', '/dklasik'),
        ('Anna karenina  lev tolstoy', '/dklasik'),
        ('anna karenina  lev tolstoy', '/dklasik'),
        ('tolstoy', '/dklasik'),
        ('Tolstoy', '/dklasik'),
        ('Lev', '/dklasik'),
        ('lev', '/dklasik'),
        ('Lev tolstoy', '/dklasik'),
        ('Lev Tolstoy', '/dklasik'),
        ('lev tolstoy', '/dklasik'),
        
        ('Aşk', '/dklasik'),
        ('Ask', '/dklasik'),
        ('ask', '/dklasik'),
        ('Ask', '/dklasik'),
        ('Ask ve gurur', '/dklasik'),
        ('ask ve gurur', '/dklasik'),
        ('Ask ve Gurur', '/dklasik'),
        ('Aşk ve Gurur', '/dklasik'),
        ('aşk ve gurur', '/dklasik'),
        ('Jane Austen', '/dklasik'),
        ('jane austen', '/dklasik'),
        ('Aşk ve Gurur  Jane Austen', '/dklasik'),
        ('Ask ve Gurur  Jane Austen', '/dklasik'),
        ('Aşk ve gurur  jane austen', '/dklasik'),
        ('Ask ve gurur  jane austen', '/dklasik'),
        ('aşk ve gurur  Jane Austen', '/dklasik'),
        ('ask ve gurur  jane austen', '/dklasik'),
        
        ('Romeo ve Juliet  ', '/dklasik'),
        ('romeo ve juliet  ', '/dklasik'),
        ('Romeo', '/dklasik'),
        ('romeo', '/dklasik'),
        ('Juliet  ', '/dklasik'),
        ('juliet', '/dklasik'),
        ('romeo ve juliet', '/dklasik'),
        ('Romeo ve juliet  ', '/dklasik'),
        ('William Shakespeare', '/dklasik'),
        ('William', '/dklasik'),
        ('william', '/dklasik'),
        ('shakespeare', '/dklasik'),
        ('Shakespeare', '/dklasik'),
        ('Romeo ve Juliet  William Shakespeare', '/dklasik'),
        ('Romeo ve juliet  william shakespeare', '/dklasik'),
        ('romeo ve juliet  william shakespeare', '/dklasik'),
        
        ('Babalar ve Oğullar', '/dklasik'),
        ('babalar ve oğullar ', '/dklasik'),
        ('Babalar', '/dklasik'),
        ('babalar', '/dklasik'),
        ('Oğullar', '/dklasik'),
        ('Ogullar', '/dklasik'),
        ('oğullar', '/dklasik'),
        ('ogullar', '/dklasik'),
        ('Ivan Turgenyev', '/dklasik'),
        ('ivan turgenyev', '/dklasik'),
        ('Babalar ve Oğullar  Ivan Turgenyev', '/dklasik'),
        ('Babalar ve oğullar  ivan turgenyev', '/dklasik'),
        ('babalar ve oğullar  ivan turgenyev', '/dklasik'),
        
        ('Ana', '/dklasik'),
        ('ana', '/dklasik'),
        ('Maksim Gorki', '/dklasik'),
        ('Maksim', '/dklasik'),
        ('maksim', '/dklasik'),
        ('Gorki', '/dklasik'),
        ('gorki', '/dklasik'),
        ('maksim gorki', '/dklasik'),
        ('Ana Maksim Gorki', '/dklasik'),
        ('Ana maksim gorki', '/dklasik'),
        ('ana maksim gorki', '/dklasik'),
        
        ('İki Şehrin Hikayesi ', '/dklasik'),
        ('İki Sehrin Hikayesi ', '/dklasik'),
        ('İki sehrin hikayesi ', '/dklasik'),
        ('iki sehrin hikayesi ', '/dklasik'),
        ('iki şehrin hikayesi', '/dklasik'),
        ('İki Sehir ', '/dklasik'),
        ('İki Şehir ', '/dklasik'),
        ('İki sehir ', '/dklasik'),
        ('iki sehir ', '/dklasik'),
        ('İki Şehir ', '/dklasik'),
        ('İki şehir ', '/dklasik'),
        ('iki şehir ', '/dklasik'),
        ('Charles Dickens', '/dklasik'),
        ('charles dickens', '/dklasik'),
        ('İki Şehrin Hikayesi  Charles Dickens', '/dklasik'),
        ('İki Sehrin Hikayesi  Charles Dickens', '/dklasik'),
        ('İki şehrin hikayesi  charles dickens', '/dklasik'),
        ('iki şehrin hikayesi  charles dickens', '/dklasik'),
        ('iki sehrin hikayesi  charles dickens', '/dklasik'),
        ('İki sehrin hikayesi  charles dickens', '/dklasik'),
        
        ('Savaş ve Barış', '/dklasik'),
        ('Savas ve Barıs', '/dklasik'),
        ('Savaş ve Bariş', '/dklasik'),
        ('Savas ve Baris', '/dklasik'),
        ('savaş ve barış', '/dklasik'),
        ('savas ve baris', '/dklasik'),
        ('Savaş', '/dklasik'),
        ('Savas', '/dklasik'),
        ('Barış', '/dklasik'),
        ('Barıs', '/dklasik'),
        ('Lev Tolstoy', '/dklasik'),
        ('lev tolstoy', '/dklasik'),
        ('Lev', '/dklasik'),
        ('lev', '/dklasik'),
        ('Tolstoy', '/dklasik'),
        ('tolstoy', '/dklasik'),
        ('Savaş ve Barış  Lev Tolstoy', '/dklasik'),
        ('Savas ve Barıs  Lev Tolstoy', '/dklasik'),
        ('savaş ve barış  lev tolstoy', '/dklasik'),
        ('Savaş ve barış  lev tolstoy', '/dklasik'),
        ('Savas ve barıs  lev tolstoy', '/dklasik'),
        ('Savaş ve Bariş  Lev Tolstoy', '/dklasik'),
        ('Savas ve Baris  Lev Tolstoy', '/dklasik'),
        ('savaş ve bariş  lev tolstoy', '/dklasik'),
        ('Savaş ve bariş  lev tolstoy', '/dklasik'),
        ('Savas ve baris  lev tolstoy', '/dklasik'),
        
        ('Kırmızı ve Siyah', '/dklasik'),
        ('Kırmızı ve siyah', '/dklasik'),
        ('Kirmizi ve Siyah', '/dklasik'),
        ('Kirmizi ve siyah', '/dklasik'),
        ('Kırmızı', '/dklasik'),
        ('kırmızı', '/dklasik'),
        ('Kirmizi', '/dklasik'),
        ('kirmizi', '/dklasik'),
        ('Stendhal', '/dklasik'),
        ('Stendhal', '/dklasik'),
        ('kırmızı ve siyah  stendhal', '/dklasik'),
        ('Kırmızı ve Siyah  Stendhal', '/dklasik'),
        ('Kırmızı ve siyah  stendhal', '/dklasik'),
        ('kirmizi ve siyah  stendhal', '/dklasik'),
        ('Kirmizi ve Siyah  Stendhal', '/dklasik'),
        ('Kirmizi ve siyah  stendhal', '/dklasik'),
        
        ('Üç Silahşörler ', '/dklasik'),
        ('üç silahşörler ', '/dklasik'),
        ('Üc Silahşörler ', '/dklasik'),
        ('üc silahşörler ', '/dklasik'),
        ('3 Silahşörler ', '/dklasik'),
        ('3 silahşörler', '/dklasik'),
        ('Alexandre Dumas', '/dklasik'),
        ('alexandre dumas', '/dklasik'),
        ('Üç Silahşörler  Alexandre Dumas', '/dklasik'),
        ('Üç silahşörler  alexandre dumas', '/dklasik'),
        ('Uc Silahsorler  Alexandre Dumas', '/dklasik'),
        ('uc silahsorler  alexandre dumas', '/dklasik'),
        
        #Türk Klasikleri-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ('İntibah', '/tklasik'),
        ('intibah', '/tklasik'),
        ('Namık Kemal', '/tklasik'),
        ('namık kemal', '/tklasik'),
        ('Namık', '/tklasik'),
        ('namık', '/tklasik'),
        ('Namık kemal', '/tklasik'),
        ('intibah  namık kemal', '/tklasik'),
        ('İntibah  namık kemal', '/tklasik'),
        ('İntibah  Namık Kemal', '/tklasik'),
    
        ('Eylül ', '/tklasik'),
        ('eylül ', '/tklasik'),
        ('Eylul ', '/tklasik'),
        ('eylul ', '/tklasik'),
        ('Mehmet Rauf', '/tklasik'), 
        ('mehmet rauf', '/tklasik'),
        ('eylül mehmet rauf', '/tklasik'),
        ('Eylül mehmet rauf', '/tklasik'),
        ('Eylül Mehmet Rauf', '/tklasik'),
        ('eylul mehmet rauf', '/tklasik'),
        ('Eylul mehmet rauf', '/tklasik'),
        ('Eylul Mehmet Rauf', '/tklasik'),
        
        ('Mai ve Siyah', '/tklasik'),
        ('mai ve siyah', '/tklasik'),
        ('Mavi ve Siyah', '/tklasik'),
        ('mavi ve siyah', '/tklasik'),
        ('Halit Ziya Uşaklıgil', '/tklasik'),
        ('halit ziya uşaklıgil', '/tklasik'),
        ('mai ve siyah  halit ziya uşaklıgil', '/tklasik'),
        ('Mai ve Siyah  Halit Ziya Uşaklıgil', '/tklasik'),
        ('mavi ve siyah  halit ziya uşaklıgil', '/tklasik'),
        ('Mavi ve Siyah  Halit Ziya Uşaklıgil', '/tklasik'),
        
        ('Cezmi', '/tklasik'),
        ('cezmi', '/tklasik'),
        ('namık kemal', '/tklasik'),
        ('Namık Kemal', '/tklasik'),
        ('cezmi  namık kemal', '/tklasik'),
        ('Cezmi  namık kemal', '/tklasik'),
        ('Cezmi  Namık Kemal', '/tklasik'),
        
        ('Esrar-ı Cinayet', '/tklasik'),
        ('esrar-ı cinayet', '/tklasik'),
        ('Esrarı Cinayet', '/tklasik'),
        ('esrarı cinayet', '/tklasik'),
        ('Ahmet Mithat Efendi', '/tklasik'),
        ('ahmet mithat efendi', '/tklasik'),
        ('Esrar-ı Cinayet Ahmet Mithat Efendi', '/tklasik'),
        ('esrar-ı cinayet ahmet mithat efendi', '/tklasik'),
        
        ('Ateşten Gömlek', '/tklasik'),
        ('ateşten gömlek', '/tklasik'),
        ('Halide Edip Adıvar', '/tklasik'),
        ('halide edip adıvar', '/tklasik'),
        ('Halide Edip', '/tklasik'),
        ('halide edip', '/tklasik'),
        ('Atesten Gomlek Halide Edip Adivar', '/tklasik'),
        ('ateşten gömlek halide edip adıvar', '/tklasik'),
        ('Atesten Gomlek Halide Edip', '/tklasik'),
        ('ateşten gömlek halide edip', '/tklasik'),
        
        # #Bilim Kurgu-------------------------------------------------------------------------------------------------------------
        # Olasılıksız, Adam Fawer
        ('Olasılıksız', '/bilimk'),
        ('olasılıksız', '/bilimk'),
        ('Olasiliksiz', '/bilimk'),
        ('olasiliksiz', '/bilimk'),
        ('Adam', '/bilimk'),
        ('adam', '/bilimk'),
        ('Fawer', '/bilimk'),
        ('fawer', '/bilimk'),
        ('Olasılıksız Adam Fawer', '/bilimk'),
        ('Olasiliksiz Adam Fawer', '/bilimk'),
        ('Olasılıksız adam fawer', '/bilimk'),
        ('Olasiliksiz adam fawer', '/bilimk'),
        ('olasılıksız adam fawer', '/bilimk'),
        ('olasiliksiz adam fawer', '/bilimk'),
        ('Olasılıksız Adam', '/bilimk'),
        ('Olasiliksiz Adam', '/bilimk'),
        ('Olasılıksız adam', '/bilimk'),
        ('Olasiliksiz adam', '/bilimk'),
        ('olasılıksız adam', '/bilimk'),
        ('olasiliksiz adam', '/bilimk'),
        
        # Görünmez Adam ,H. G.Wells
        ('Görünmez Adam', '/bilimk'),
        ('Görünmez adam', '/bilimk'),
        ('görünmez adam', '/bilimk'),
        ('Görünmez', '/bilimk'),
        ('görünmez', '/bilimk'),
        ('H G Wells', '/bilimk'),
        ('HG Wells', '/bilimk'),
        ('H G wells', '/bilimk'),
        ('HG wells', '/bilimk'),
        ('H g wells', '/bilimk'),
        ('Hg wells', '/bilimk'),
        ('Wells', '/bilimk'),
        ('wells', '/bilimk'),
        ('Görünmez Adam H G Wells', '/bilimk'),
        ('Görünmez adam h g wells', '/bilimk'),
        ('görünmez adam h g wells', '/bilimk'),
        
        # Dune ,Frank Herbert
        ('Dune', '/bilimk'),
        ('dune', '/bilimk'),
        ('Frank', '/bilimk'),
        ('frank', '/bilimk'),
        ('Frank Herbert', '/bilimk'),
        ('Frank herbert', '/bilimk'),
        ('frank herbert', '/bilimk'),
        ('Dune Frank Herbert', '/bilimk'),
        ('Dune frank herbert', '/bilimk'),
        ('dune frank herbert', '/bilimk'),
        
        # Fahrenheit 451 ,Ray Bradbury
        ('Fahrenheit', '/bilimk'),
        ('fahrenheit', '/bilimk'),
        ('Fahrenheit 451', '/bilimk'),
        ('fahrenheit 451', '/bilimk'),
        ('451', '/bilimk'),
        ('Ray Bradbury', '/bilimk'),
        ('Ray bradbury', '/bilimk'),
        ('ray bradbury', '/bilimk'),
        ('Ray', '/bilimk'),
        ('bradbury', '/bilimk'),
        ('ray', '/bilimk'),
        ('Bradbury', '/bilimk'),
        ('Fahrenheit 451 Ray Bradbury', '/bilimk'),
        ('Fahrenheit 451 ray bradbury', '/bilimk'),
        ('fahrenheit 451 ray bradbury', '/bilimk'),
        
        # Üç Cisim Problemi ,Cixin Liu
        ('Üç Cisim Problemi', '/bilimk'),
        ('Üç cisim problemi', '/bilimk'),
        ('üç cisim problemi', '/bilimk'),
        ('Üc Cisim Problemi', '/bilimk'),
        ('Üc cisim problemi', '/bilimk'),
        ('üc cisim problemi', '/bilimk'),
        ('Uc Cisim Problemi', '/bilimk'),
        ('Uc cisim problemi', '/bilimk'),
        ('uc cisim problemi', '/bilimk'),
        ('Üç Cisim', '/bilimk'),
        ('Üç cisim', '/bilimk'),
        ('üç cisim', '/bilimk'),
        ('Üc Cisim', '/bilimk'),
        ('Üc cisim', '/bilimk'),
        ('üc cisim', '/bilimk'),
        ('Uc Cisim', '/bilimk'),
        ('Uc cisim', '/bilimk'),
        ('uc cisim', '/bilimk'),
        ('Cixin Liu', '/bilimk'),
        ('Cixin liu', '/bilimk'),
        ('cixin liu', '/bilimk'),
        ('cixin', '/bilimk'),
        ('Cixin', '/bilimk'),
        ('liu', '/bilimk'),
        ('Liu', '/bilimk'),
        ('Üç Cisim Problemi Cixin Liu', '/bilimk'),
        ('Üç cisim problemi cixin liu', '/bilimk'),
        ('Üc Cisim Problemi Cixin Liu', '/bilimk'),
        ('Üc cisim problemi cixin liu', '/bilimk'),
        ('Uc Cisim Problemi Cixin Liu', '/bilimk'),
        ('Uc cisim problemi cixin liu', '/bilimk'),
        
        # 1984 ,George Orwell
        ('1984', '/bilimk'),
        ('George Orwell', '/bilimk'),
        ('George orwell', '/bilimk'),
        ('george orwell', '/bilimk'),
        ('George', '/bilimk'),
        ('george', '/bilimk'),
        ('Orwell', '/bilimk'),
        ('orwell', '/bilimk'),
        ('1984 George Orwell', '/bilimk'),
        ('1984 George orwell', '/bilimk'),
        ('1984 george orwell', '/bilimk'),
        
        # Göçebe ,Stephenie Meyer
        ('Göçebe', '/bilimk'),
        ('göçebe', '/bilimk'),
        ('Göcebe', '/bilimk'),
        ('göcebe', '/bilimk'),
        ('Goçebe', '/bilimk'),
        ('goçebe', '/bilimk'),
        ('Gocebe', '/bilimk'),
        ('gocebe', '/bilimk'),
        ('Stephenie Meyer', '/bilimk'),
        ('Stephenie meyer', '/bilimk'),
        ('Stephenie', '/bilimk'),
        ('stephenie', '/bilimk'),
        ('Meyer', '/bilimk'),
        ('meyer', '/bilimk'),
        ('Göçebe Stephenie Meyer', '/bilimk'),
        ('Göçebe stephenie meyer', '/bilimk'),
        ('göçebe stephenie meyer', '/bilimk'),
        ('Goçebe Stephenie Meyer', '/bilimk'),
        ('Goçebe stephenie meyer', '/bilimk'),
        ('goçebe stephenie meyer', '/bilimk'),
        ('Göcebe Stephenie Meyer', '/bilimk'),
        ('Göcebe stephenie meyer', '/bilimk'),
        ('göcebe stephenie meyer', '/bilimk'),
        ('Gocebe Stephenie Meyer', '/bilimk'),
        ('Gocebe stephenie meyer', '/bilimk'),
        ('gocebe stephenie meyer', '/bilimk'),
            
        # Mülksüzler ,Ursula K. Le Guin
        ('Mülksüzler', '/bilimk'),
        ('mülksüzler', '/bilimk'),
        ('Ursula K. Le Guin', '/bilimk'),
        ('Ursula k. le guin', '/bilimk'),
        ('ursula k. le guin', '/bilimk'),
        ('Ursula K Le Guin', '/bilimk'),
        ('Ursula k le guin', '/bilimk'),
        ('ursula k le guin', '/bilimk'),
        ('Mülksüzler Ursula K. Le Guin', '/bilimk'),
        ('Mülksüzler ursula k. le guin', '/bilimk'),
        ('mülksüzler ursula k. le guin', '/bilimk'),
        ('Mülksüzler Ursula K Le Guin', '/bilimk'),
        ('Mülksüzler ursula k le guin', '/bilimk'),
        ('mülksüzler ursula k le guin', '/bilimk'),
        
        # #Polisiye--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        # Doğu Ekspresinde Cinayet ,Agatha Christie
        ('Doğu Ekspresinde Cinayet', '/polisiye'),
        ('Doğu ekspresinde cinayet', '/polisiye'),
        ('Doğu Ekspresinde', '/polisiye'),
        ('Doğu ekspresinde', '/polisiye'),
        ('Dogu Ekspresinde Cinayet', '/polisiye'),
        ('Dogu ekspresinde cinayet', '/polisiye'),
        ('Dogu Ekspresinde', '/polisiye'),
        ('Dogu ekspresinde', '/polisiye'),
        ('Agatha', '/polisiye'),
        ('agatha', '/polisiye'),
        ('Christie', '/polisiye'),
        ('christie', '/polisiye'),
        ('Agatha Christie', '/polisiye'),
        ('Agatha christie', '/polisiye'),
        ('agatha christie', '/polisiye'),
        ('Doğu Ekspresinde Cinayet Agatha Christie', '/polisiye'),
        ('Doğu ekspresinde cinayet agatha christie', '/polisiye'),
        ('doğu ekspresinde cinayet agatha christie', '/polisiye'),
        ('Dogu Ekspresinde Cinayet Agatha Christie', '/polisiye'),
        ('Dogu ekspresinde cinayet agatha christie', '/polisiye'),
        ('dogu ekspresinde cinayet agatha christie', '/polisiye'),
        
        # Ahmet Ümit ,Beyoğlu Rapsodisi
        ('Beyoğlu Rapsodisi', '/polisiye'),
        ('Beyoğlu rapsodisi', '/polisiye'),
        ('beyoğlu rapsodisi', '/polisiye'),
        ('Beyoğlu', '/polisiye'),
        ('beyoğlu', '/polisiye'),
        ('Beyoglu Rapsodisi', '/polisiye'),
        ('Beyoglu rapsodisi', '/polisiye'),
        ('beyoglu rapsodisi', '/polisiye'),
        ('Beyoglu', '/polisiye'),
        ('beyoglu', '/polisiye'),
        ('Ahmet Ümit', '/polisiye'),
        ('Ahmet ümit', '/polisiye'),
        ('ahmet ümit', '/polisiye'),
        ('Beyoğlu Rapsodisi Ahmet Ümit', '/polisiye'),
        ('Beyoğlu rapsodisi ahmet ümit', '/polisiye'),
        ('beyoğlu rapsodisi ahmet ümit', '/polisiye'),
        ('Beyoglu Rapsodisi Ahmet Ümit', '/polisiye'),
        ('Beyoglu rapsodisi ahmet ümit', '/polisiye'),
        ('beyoglu rapsodisi ahmet ümit', '/polisiye'),
        
        # Hayvan Mezarlığı ,Stephen King
        ('Hayvan Mezarlığı', '/polisiye'),
        ('Hayvan mezarlığı', '/polisiye'),
        ('hayvan mezarlığı', '/polisiye'),
        ('Hayvan Mezarlıgı', '/polisiye'),
        ('Hayvan mezarlıgı', '/polisiye'),
        ('hayvan mezarlıgı', '/polisiye'),
        ('Stephen King', '/polisiye'),
        ('Stephen king', '/polisiye'),
        ('stephen king', '/polisiye'),
        ('Stephen', '/polisiye'),
        ('stephen', '/polisiye'),
        ('King', '/polisiye'),
        ('king', '/polisiye'),
        ('Hayvan Mezarlığı Stephen King', '/polisiye'),
        ('Hayvan mezarlığı stephen king', '/polisiye'),
        ('hayvan mezarlığı stephen king', '/polisiye'),
        ('Hayvan Mezarlıgı Stephen King', '/polisiye'),
        ('Hayvan mezarlıgı stephen king', '/polisiye'),
        ('hayvan mezarlıgı stephen king', '/polisiye'),
        
        # Siyah Kan ,Jean Christophe Grangé
        ('Siyah Kan', '/polisiye'),
        ('Siyah kan', '/polisiye'),
        ('siyah kan', '/polisiye'),
        ('Jean Christophe Grangé', '/polisiye'),
        ('Jean christophe grangé', '/polisiye'),
        ('jean christophe grangé', '/polisiye'),
        ('Jean Christophe Grange', '/polisiye'),
        ('Jean christophe grange', '/polisiye'),
        ('jean christophe grange', '/polisiye'),
        ('Jean Christophe', '/polisiye'),
        ('Jean christophe', '/polisiye'),
        ('jean christophe', '/polisiye'),
        ('Siyah Kan Jean Christophe Grangé', '/polisiye'),
        ('Siyah kan jean christophe grangé', '/polisiye'),
        ('siyah kan jean christophe grangé', '/polisiye'),
        ('Siyah Kan Jean Christophe Grange', '/polisiye'),
        ('Siyah kan jean christophe grange', '/polisiye'),
        ('siyah kan jean christophe grange', '/polisiye'),
        
        # Çırak ,Tess Gerritsen
        ('Çırak', '/polisiye'),
        ('çırak', '/polisiye'),
        ('Cırak', '/polisiye'),
        ('cırak', '/polisiye'),
        ('Çirak', '/polisiye'),
        ('çirak', '/polisiye'),
        ('Cirak', '/polisiye'),
        ('cirak', '/polisiye'),
        ('Tess Gerritsen', '/polisiye'),
        ('Tess gerritsen', '/polisiye'),
        ('tess gerritsen', '/polisiye'),
        ('Tess', '/polisiye'),
        ('tess', '/polisiye'),
        ('Gerritsen', '/polisiye'),
        ('gerritsen', '/polisiye'),
        ('Çırak Tess Gerritsen', '/polisiye'),
        ('Çırak tess gerritsen', '/polisiye'),
        ('çırak tess gerritsen', '/polisiye'),
        ('Cırak Tess Gerritsen', '/polisiye'),
        ('Cırak tess gerritsen', '/polisiye'),
        ('cırak tess gerritsen', '/polisiye'),
        ('Çirak Tess Gerritsen', '/polisiye'),
        ('Çirak tess gerritsen', '/polisiye'),
        ('çirak tess gerritsen', '/polisiye'),
        ('Cirak Tess Gerritsen', '/polisiye'),
        ('Cirak tess gerritsen', '/polisiye'),
        ('cirak tess gerritsen', '/polisiye'),
        
        # Cehennem ,Dan Brown
        ('Cehennem', '/polisiye'),
        ('cehennem', '/polisiye'),
        ('Dan', '/polisiye'),
        ('dan', '/polisiye'),
        ('Brown', '/polisiye'),
        ('brown', '/polisiye'),
        ('Dan Brown', '/polisiye'),
        ('Dan brown', '/polisiye'),
        ('dan brown', '/polisiye'),
        ('Cehennem Dan Brown', '/polisiye'),
        ('Cehennem dan brown', '/polisiye'),
        ('cehennem dan brown', '/polisiye'),
        
        # Mathilda ,Mary Shelley
        ('Mathilda', '/polisiye'),
        ('mathilda', '/polisiye'),
        ('Mary', '/polisiye'),
        ('mary', '/polisiye'),
        ('Shelley', '/polisiye'),
        ('shelley', '/polisiye'),
        ('Mary Shelley', '/polisiye'),
        ('Mary shelley', '/polisiye'),
        ('mary shelley', '/polisiye'),
        ('Mathilda Mary Shelley', '/polisiye'),
        ('Mathilda mary shelley', '/polisiye'),
        ('mathilda mary shelley', '/polisiye'),
        
        # Siyah İnci ,Anna Sewell
        ('Siyah İnci', '/polisiye'),
        ('Siyah inci', '/polisiye'),
        ('siyah inci', '/polisiye'),
        ('Anna Sewell', '/polisiye'),
        ('Anna sewell', '/polisiye'),
        ('anna sewell', '/polisiye'),
        ('Siyah İnci Anna Sewell', '/polisiye'),
        ('Siyah inci anna sewell', '/polisiye'),
        ('siyah inci anna sewell', '/polisiye'),
        
        # #Romanlar-----------------
        # Serenad Zülfü Livaneli
        ('Serenad', '/romanlar'),
        ('serenad', '/romanlar'),
        ('Zülfü livaneli', '/romanlar'),
        ('zülfü livaneli', '/romanlar'),
        ('Livaneli', '/romanlar'),
        ('livaneli', '/romanlar'),
        ('Zülfü', '/romanlar'),
        ('zülfü', '/romanlar'),
        ('Serenad Zülfü Livaneli', '/romanlar'),
        ('Serenad zülfü livaneli', '/romanlar'),
        ('serenad zülfü livaneli', '/romanlar'),
        
        # Kürk Mantolu Madonna ,Sabahattin Ali
        ('Kürk Mantolu Madonna', '/romanlar'),
        ('Kürk mantolu madonna', '/romanlar'),
        ('kürk mantolu madonna', '/romanlar'),
        ('Sabahattin Ali', '/romanlar'),
        ('Sabahattin ali', '/romanlar'),
        ('sabahattin ali', '/romanlar'),
        ('Sabahattinali', '/romanlar'),
        ('sabahattinali', '/romanlar'),
        ('Kürk Mantolu Madonna Sabahattin Ali', '/romanlar'),
        ('Kürk mantolu madonna sabahattin ali', '/romanlar'),
        ('kürk mantolu madonna sabahattin ali', '/romanlar'),
        ('Kürk Mantolu Madonna SabahattinAli', '/romanlar'),
        ('Kürk mantolu madonna sabahattinali', '/romanlar'),
        ('kürk mantolu madonna sabahattinali', '/romanlar'),
        
        # Uçurtma Avcısı ,Khaled Hosseini
        ('Uçurtma Avcısı', '/romanlar'),
        ('Uçurtma avcısı', '/romanlar'),
        ('uçurtma avcısı', '/romanlar'),
        ('Uçurtma Avcisi', '/romanlar'),
        ('Uçurtma avcisi', '/romanlar'),
        ('uçurtma avcisi', '/romanlar'),
        ('Ucurtma Avcısı', '/romanlar'),
        ('Ucurtma avcısı', '/romanlar'),
        ('ucurtma avcısı', '/romanlar'),
        ('Ucurtma Avcisi', '/romanlar'),
        ('Ucurtma avcisi', '/romanlar'),
        ('ucurtma avcisi', '/romanlar'),
        ('Uçurtma', '/romanlar'),
        ('Ucurtma', '/romanlar'),
        ('uçurtma', '/romanlar'),
        ('uçurtma Avcısı', '/romanlar'),
        ('Khaled Hosseini', '/romanlar'),
        ('Khaled hosseini', '/romanlar'),
        ('khaled hosseini', '/romanlar'),
        ('Uçurtma Avcısı Khaled Hosseini', '/romanlar'),
        ('Uçurtma avcısı khaled hosseini', '/romanlar'),
        ('uçurtma avcısı khaled hosseini', '/romanlar'),
        ('Uçurtma Avcisi Khaled Hosseini', '/romanlar'),
        ('Uçurtma avcisi khaled hosseini', '/romanlar'),
        ('uçurtma avcisi khaled hosseini', '/romanlar'),
        ('Ucurtma Avcısı Khaled Hosseini', '/romanlar'),
        ('Ucurtma avcısı khaled hosseini', '/romanlar'),
        ('ucurtma avcısı khaled hosseini', '/romanlar'),
        ('Ucurtma Avcisi Khaled Hosseini', '/romanlar'),
        ('Ucurtma avcisi khaled hosseini', '/romanlar'),
        ('ucurtma avcisi khaled hosseini', '/romanlar'),
        
        # Aşkımız Eski Bir Roman ,Ahmet Ümit
        ('Aşkımız Eski Bir Roman', '/romanlar'),
        ('Aşkımız eski bir roman', '/romanlar'),
        ('aşkımız eski bir roman', '/romanlar'),
        ('Askımız Eski Bir Roman', '/romanlar'),
        ('Askımız eski bir roman', '/romanlar'),
        ('askımız eski bir roman', '/romanlar'),
        ('Ahmet Ümit', '/romanlar'),
        ('Ahmet ümit', '/romanlar'),
        ('ahmet ümit', '/romanlar'),
        ('Ahmet umit', '/romanlar'),
        ('ahmet umit', '/romanlar'),
        ('Aşkımız Eski Bir Roman Ahmet Ümit', '/romanlar'),
        ('Aşkımız eski bir roman ahmet ümit', '/romanlar'),
        ('aşkımız eski bir roman ahmet ümit', '/romanlar'),
        ('Aşkımız eski bir roman ahmet umit', '/romanlar'),
        ('aşkımız eski bir roman ahmet umit', '/romanlar'),
        ('Askımız Eski Bir Roman Ahmet Ümit', '/romanlar'),
        ('Askımız eski bir roman ahmet ümit', '/romanlar'),
        ('askımız eski bir roman ahmet ümit', '/romanlar'),
        ('Askımız eski bir roman ahmet umit', '/romanlar'),
        ('askımız eski bir roman ahmet umit', '/romanlar'),
        
        # Dönüşüm ,Franz Kafka
        ('Dönüşüm', '/romanlar'),
        ('Dönüsüm', '/romanlar'),
        ('Donusum', '/romanlar'),
        ('dönüşüm', '/romanlar'),
        ('dönüsüm', '/romanlar'),
        ('donusum', '/romanlar'),
        ('Franz Kafka', '/romanlar'),
        ('Franz kafka', '/romanlar'),
        ('franz kafka', '/romanlar'),
        ('Kafka', '/romanlar'),
        ('kafka', '/romanlar'),
        ('Franz', '/romanlar'),
        ('franz', '/romanlar'),
        ('Dönüşüm Franz Kafka', '/romanlar'),
        ('Dönüşüm franz kafka', '/romanlar'),
        ('dönüşüm franz kafka', '/romanlar'),
        ('Dönüsüm Franz Kafka', '/romanlar'),
        ('Dönüsüm franz kafka', '/romanlar'),
        ('dönüsüm franz kafka', '/romanlar'),
    
        # Bir Ömür Nasıl Yaşanır? ,İlber Ortaylı
        ('Bir Ömür Nasıl Yaşanır?', '/romanlar'),
        ('Bir ömür nasıl yaşanır?', '/romanlar'),
        ('bir ömür nasıl yaşanır?', '/romanlar'),
        ('Bir Ömür Nasıl Yasanır?', '/romanlar'),
        ('Bir ömür nasıl yasanır?', '/romanlar'),
        ('bir ömür nasıl yasanır?', '/romanlar'),
        ('Bir Ömur Nasıl Yaşanır?', '/romanlar'),
        ('Bir ömur nasıl yaşanır?', '/romanlar'),
        ('bir ömur nasıl yaşanır?', '/romanlar'),
        ('Bir Ömur Nasıl Yasanır?', '/romanlar'),
        ('Bir ömur nasıl yasanır?', '/romanlar'),
        ('bir ömur nasıl yasanır?', '/romanlar'),
        ('Bir Omür Nasıl Yaşanır?', '/romanlar'),
        ('Bir omür nasıl yaşanır?', '/romanlar'),
        ('bir omür nasıl yaşanır?', '/romanlar'),
        ('Bir Omür Nasıl Yasanır?', '/romanlar'),
        ('Bir omür nasıl yasanır?', '/romanlar'),
        ('bir omür nasıl yasanır?', '/romanlar'),
        ('Bir Omur Nasıl Yaşanır?', '/romanlar'),
        ('Bir omur nasıl yaşanır?', '/romanlar'),
        ('bir omur nasıl yaşanır?', '/romanlar'),
        ('Bir Omur Nasıl Yasanır?', '/romanlar'),
        ('Bir omur nasıl yasanır?', '/romanlar'),
        ('bir omur nasıl yasanır?', '/romanlar'),
        
        ('Bir Ömür Nasıl Yaşanır', '/romanlar'),
        ('Bir ömür nasıl yaşanır', '/romanlar'),
        ('bir ömür nasıl yaşanır', '/romanlar'),
        ('Bir Ömür Nasıl Yasanır', '/romanlar'),
        ('Bir ömür nasıl yasanır', '/romanlar'),
        ('bir ömür nasıl yasanır', '/romanlar'),
        ('Bir Ömur Nasıl Yaşanır', '/romanlar'),
        ('Bir ömur nasıl yaşanır', '/romanlar'),
        ('bir ömur nasıl yaşanır', '/romanlar'),
        ('Bir Ömur Nasıl Yasanır', '/romanlar'),
        ('Bir ömur nasıl yasanır', '/romanlar'),
        ('bir ömur nasıl yasanır', '/romanlar'),
        ('Bir Omür Nasıl Yaşanır', '/romanlar'),
        ('Bir omür nasıl yaşanır', '/romanlar'),
        ('bir omür nasıl yaşanır', '/romanlar'),
        ('Bir Omür Nasıl Yasanır', '/romanlar'),
        ('Bir omür nasıl yasanır', '/romanlar'),
        ('bir omür nasıl yasanır', '/romanlar'),
        ('Bir Omur Nasıl Yaşanır', '/romanlar'),
        ('Bir omur nasıl yaşanır', '/romanlar'),
        ('bir omur nasıl yaşanır', '/romanlar'),
        ('Bir Omur Nasıl Yasanır', '/romanlar'),
        ('Bir omur nasıl yasanır', '/romanlar'),
        ('bir omur nasıl yasanır', '/romanlar'),
        
        ('İlber Ortaylı', '/romanlar'),
        ('İlber ortaylı', '/romanlar'),
        ('ilber ortaylı', '/romanlar'),
        ('İlber', '/romanlar'),
        ('ilber', '/romanlar'),
        ('Ortaylı', '/romanlar'),
        ('ortaylı', '/romanlar'),
        ('Ortayli', '/romanlar'),
        ('ortayli', '/romanlar'),
        ('Bir Ömür Nasıl Yaşanır? İlber Ortaylı', '/romanlar'),
        ('Bir ömür nasıl yaşanır? ilber ortaylı', '/romanlar'),
        ('bir ömür nasıl yaşanır? ilber ortaylı', '/romanlar'),
        ('Bir Omur Nasil Yasanir? İlber Ortayli', '/romanlar'),
        ('Bir omur nasil yasanir? ilber ortayli', '/romanlar'),
        ('bir omur nasil yasanir? ilber ortaylı', '/romanlar'),
        ('Bir Ömür Nasıl Yaşanır İlber Ortaylı', '/romanlar'),
        ('Bir ömür nasıl yaşanır ilber ortaylı', '/romanlar'),
        ('bir ömür nasıl yaşanır ilber ortaylı', '/romanlar'),
        ('Bir Omur Nasil Yasanir İlber Ortayli', '/romanlar'),
        ('Bir omur nasil yasanir ilber ortayli', '/romanlar'),
        ('bir omur nasil yasanir ilber ortaylı', '/romanlar'),
    
        # Altın Gözde Yansımalar ,Carson McCullers
        ('Altın Gözde Yansımalar', '/romanlar'),
        ('Altın gözde yansımalar', '/romanlar'),
        ('altın gözde yansımalar', '/romanlar'),
        ('Altin Gözde Yansimalar', '/romanlar'),
        ('Altin gözde yansimalar', '/romanlar'),
        ('altin gözde yansimalar', '/romanlar'),
        ('Altın Gozde Yansımalar', '/romanlar'),
        ('Altın gozde yansımalar', '/romanlar'),
        ('altın gozde yansımalar', '/romanlar'),
        ('Altin Gozde Yansimalar', '/romanlar'),
        ('Altin gozde yansimalar', '/romanlar'),
        ('altin gozde yansimalar', '/romanlar'),
        ('Carson McCullers', '/romanlar'),
        ('Carson mcCullers', '/romanlar'),
        ('carson mcCullers', '/romanlar'),
        ('Carson', '/romanlar'),
        ('carson', '/romanlar'),
        ('Altın Gözde Yansımalar Carson McCullers', '/romanlar'),
        ('Altın gözde yansımalar carson mcCullers', '/romanlar'),
        ('altın gözde yansımalar carson mcCullers', '/romanlar'),
        ('Altin Gözde Yansimalar Carson McCullers', '/romanlar'),
        ('Altin gözde yansimalar carson mcCullers', '/romanlar'),
        ('altin gözde yansimalar carson mcCullers', '/romanlar'),
        
        # Bilinmeyen Bir Kadının Mektubu ,Stefan Zweig
        ('Bilinmeyen Bir Kadının Mektubu', '/romanlar'),
        ('Bilinmeyen bir kadının mektubu', '/romanlar'),
        ('bilinmeyen bir kadının mektubu', '/romanlar'),
        ('Bilinmeyen Bir Kadinin Mektubu', '/romanlar'),
        ('Bilinmeyen bir kadinin mektubu', '/romanlar'),
        ('bilinmeyen bir kadinin mektubu', '/romanlar'),
        ('Bilinmeyen Bir Kadın', '/romanlar'),
        ('Bilinmeyen bir kadın', '/romanlar'),
        ('bilinmeyen bir kadın', '/romanlar'),
        ('Bilinmeyen Bir Kadin', '/romanlar'),
        ('Bilinmeyen bir kadin', '/romanlar'),
        ('bilinmeyen bir kadin', '/romanlar'),
        ('Stefan Zweig', '/romanlar'),
        ('Stefan zweig', '/romanlar'),
        ('stefan zweig', '/romanlar'),
        ('stefan', '/romanlar'),
        ('Stefan', '/romanlar'),
        ('Zweig', '/romanlar'),
        ('zweig', '/romanlar'),
        ('Bilinmeyen Bir Kadının Mektubu Stefan Zweig', '/romanlar'),
        ('Bilinmeyen bir kadının mektubu stefan zweig', '/romanlar'),
        ('bilinmeyen bir kadının mektubu stefan zweig', '/romanlar'),
        ('Bilinmeyen Bir Kadinin Mektubu Stefan Zweig', '/romanlar'),
        ('Bilinmeyen bir kadinin mektubu stefan zweig', '/romanlar'),
        ('bilinmeyen bir kadinin mektubu stefan zweig', '/romanlar'),
        
        # #Şiirler--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        # Memleketimden İnsan Manzaraları ,Nazım Hikmet
        ('Memleketimden İnsan Manzaraları', '/siirler'),
        ('Memleketimden insan manzaraları', '/siirler'),
        ('memleketimden insan manzaraları', '/siirler'),
        ('Memleketimden İnsan Manzaralari', '/siirler'),
        ('Memleketimden insan manzaralari', '/siirler'),
        ('memleketimden insan manzaralari', '/siirler'),
        ('Nazım Hikmet', '/siirler'),
        ('Nazım hikmet', '/siirler'),
        ('nazım hikmet', '/siirler'),
        ('Nazim Hikmet', '/siirler'),
        ('Nazim hikmet', '/siirler'),
        ('nazim hikmet', '/siirler'),
        ('Nazım', '/siirler'),
        ('Nazım', '/siirler'),
        ('nazım', '/siirler'),
        ('Nazim', '/siirler'),
        ('Nazim', '/siirler'),
        ('nazim', '/siirler'),
        ('Memleketimden İnsan Manzaraları Nazım Hikmet', '/siirler'),
        ('Memleketimden insan manzaraları nazım hikmet', '/siirler'),
        ('memleketimden insan manzaraları nazım Hikmet', '/siirler'),
        ('Memleketimden İnsan Manzaralari Nazım Hikmet', '/siirler'),
        ('Memleketimden insan manzaralari nazım hikmet', '/siirler'),
        ('memleketimden insan manzaralari nazım Hikmet', '/siirler'),
        
        # Sevda Sözleri ,Cemal Süreya
        ('Sevda Sözleri', '/siirler'),
        ('Sevda sözleri', '/siirler'),
        ('sevda sözleri', '/siirler'),
        ('Cemal Süreya', '/siirler'),
        ('Cemal süreya', '/siirler'),
        ('cemal süreya', '/siirler'),
        ('Sevda Sözleri Cemal Süreya', '/siirler'),
        ('Sevda sözleri cemal süreya', '/siirler'),
        ('sevda sözleri cemal süreya', '/siirler'),
        
        # Hasretinden Prangalar Eskittim ,Ahmed Arif
        ('Hasretinden Prangalar Eskittim', '/siirler'),
        ('Hasretinden prangalar eskittim', '/siirler'),
        ('hasretinden prangalar eskittim', '/siirler'),
        ('Hasretinden Prangalar', '/siirler'),
        ('Hasretinden prangalar', '/siirler'),
        ('hasretinden prangalar', '/siirler'),
        ('Prangalar Eskittim', '/siirler'),
        ('Prangalar eskittim', '/siirler'),
        ('prangalar eskittim', '/siirler'),
        ('Ahmed Arif', '/siirler'),
        ('Ahmed arif', '/siirler'),
        ('ahmed arif', '/siirler'),
        ('Hasretinden Prangalar Eskittim Ahmed Arif', '/siirler'),
        ('Hasretinden prangalar eskittim ahmed arif', '/siirler'),
        ('hasretinden prangalar eskittim ahmed arif', '/siirler'),
        
        # Yalnızlık Paylaşılmaz ,Özdemir Asaf
        ('Yalnızlık Paylaşılmaz', '/siirler'),
        ('Yalnızlık paylaşılmaz', '/siirler'),
        ('yalnızlık paylaşılmaz', '/siirler'),
        ('Yalnizlik Paylaşilmaz', '/siirler'),
        ('Yalnizlik paylaşilmaz', '/siirler'),
        ('yalnizlik paylaşilmaz', '/siirler'),
        ('Özdemir Asaf', '/siirler'),
        ('Özdemir asaf', '/siirler'),
        ('özdemir asaf', '/siirler'),
        ('Yalnızlık Paylaşılmaz Özdemir Asaf', '/siirler'),
        ('Yalnızlık paylaşılmaz özdemir asaf', '/siirler'),
        ('yalnızlık paylaşılmaz özdemir asaf', '/siirler'),
        ('Yalnizlik Paylaşilmaz Özdemir Asaf', '/siirler'),
        ('Yalnizlik paylaşilmaz özdemir asaf', '/siirler'),
        ('yalnizlik paylaşilmaz özdemir asaf', '/siirler'),
        
        # Ben Sana Mecburum ,Attila İlhan
        ('Ben Sana Mecburum', '/siirler'),
        ('Ben sana mecburum', '/siirler'),
        ('ben sana mecburum', '/siirler'),
        ('Attila İlhan', '/siirler'),
        ('Attila ilhan', '/siirler'),
        ('attila ilhan', '/siirler'),
        ('Ben Sana Mecburum Attila İlhan', '/siirler'),
        ('Ben sana mecburum attila ilhan', '/siirler'),
        ('ben sana mecburum attila ilhan', '/siirler'),
        
        # Bütün Şiirleri ,Orhan Veli Kanık
        ('Bütün Şiirleri', '/siirler'),
        ('Bütün şiirleri', '/siirler'),
        ('bütün şiirleri', '/siirler'),
        ('Bütün Siirleri', '/siirler'),
        ('Bütün siirleri', '/siirler'),
        ('bütün siirleri', '/siirler'),
        ('Orhan Veli Kanık', '/siirler'),
        ('Orhan veli kanık', '/siirler'),
        ('orhan veli kanık', '/siirler'),
        ('Orhan Veli', '/siirler'),
        ('Orhan veli', '/siirler'),
        ('orhan veli', '/siirler'),
        ('Bütün Şiirleri Orhan Veli Kanık', '/siirler'),
        ('Bütün şiirleri orhan veli kanık', '/siirler'),
        ('bütün şiirleri orhan veli kanık', '/siirler'),
        ('Bütün Siirleri Orhan Veli Kanık', '/siirler'),
        ('Bütün siirleri orhan veli kanık', '/siirler'),
        ('bütün siirleri orhan veli kanık', '/siirler'),
    
        # Çile ,Necip Fazıl Kısakürek
        ('Çile', '/siirler'),
        ('çile', '/siirler'),
        ('Cile', '/siirler'),
        ('Cile', '/siirler'), 
        ('Necip Fazıl Kısakürek', '/siirler'),
        ('Necip fazıl kısakürek', '/siirler'),
        ('necip fazıl kısakürek', '/siirler'),
        ('Necip Fazıl', '/siirler'),
        ('Necip fazıl', '/siirler'),
        ('necip fazıl', '/siirler'),
        ('Kısakürek', '/siirler'),
        ('kısakürek', '/siirler'),
        ('Çile Necip Fazıl Kısakürek', '/siirler'),
        ('Çile necip fazıl kısakürek', '/siirler'),
        ('çile necip fazıl kısakürek', '/siirler'),
        ('Cile Necip Fazıl Kısakürek', '/siirler'),
        ('Cile necip fazıl kısakürek', '/siirler'),
        ('cile necip fazıl kısakürek', '/siirler'),
        
        # Monna Rosa ,Sezai Karakoç
        ('Monna Rosa', '/siirler'),
        ('Monna rosa', '/siirler'),
        ('monna rosa', '/siirler'),
        ('Mona Rosa', '/siirler'),
        ('Mona rosa', '/siirler'),
        ('mona rosa', '/siirler'),
        ('Sezai Karakoç', '/siirler'),
        ('Sezai karakoç', '/siirler'),
        ('sezai karakoç', '/siirler'),
        ('Sezai', '/siirler'),
        ('sezai', '/siirler'),
        ('Monna Rosa Sezai Karakoç', '/siirler'),
        ('Monna rosa sezai karakoç', '/siirler'),
        ('monna rosa sezai karakoç', '/siirler'),
        ('Mona Rosa Sezai Karakoç', '/siirler'),
        ('Mona rosa sezai karakoç', '/siirler'),
        ('mona rosa sezai karakoç', '/siirler'),
        
        
       
    ]

    c.executemany('INSERT INTO sayfalar (isim, sayfa) VALUES (?, ?)', veriler)

    # Değişiklikleri kaydetme
    conn.commit()

    # Veritabanı bağlantısını kapatma
    conn.close()


if __name__ == '__main__':
    veri_ekle()
    print("Veriler basarıyla eklendi.")